server {
    listen 80;
    listen [::]:80;

    server_name backend.local.dev;

    index index.php index.html;
    root /var/www/html/backend/public;

    location / {
        try_files $uri $uri/ /index.php?$args;
        include _headers.conf;
    }

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include _fastcgi.conf;

        include _headers.conf;
    }
}
