server {
    listen 6001;
    listen [::]:6001;

    server_name ws.project;

    location / {
        proxy_pass http://soketi:6001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-Ip $remote_addr;
    }
}
