FROM quay.io/soketi/soketi:1.4-16-debian

#for config check https://docs.soketi.app/app-management/array-driver

RUN mkdir -p /etc/soketi/config

COPY websocket-config.json /etc/soketi/config/websocket-config.json

